### ISSUE TITLE
ImportError: No module named mapit_gb.controls.first-gss

### ISSUE THREAD

**Issue by ollywhitespace** [mysociety/mapit#161]
I'm attempting to import the UK OS data. I'm following the instructions here:
http://mapit.poplus.org/docs/self-hosted/import/uk/ by running:

```
./manage.py mapit_UK_import_boundary_line     --control=mapit_gb.controls.first-gss --commit     `\ls ~/Data/*.shp|\grep -v high_water`
```

Which is then displaying:

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 322, in handle
    label_output = self.handle_label(label, **options)
  File "/var/www/mapit/mapit/mapit/management/commands/mapit_UK_import_boundary_line.py", line 30, in handle_label
    __import__(options['control'])
ImportError: No module named mapit_gb.controls.first-gss
```

Do the docs just need updating here to reference `mapit.controls.first-gss` instead?

**Comment by dracos** [comment]
The documentation is further along than the version of the code installed in the AMI. If you update the code in the AMI with a git fetch and merge or similar, you should then find the code in the same place as the documentation. Let us know if you have any problems. We should release a new version of the AMI with up to date code.
