### ISSUE TITLE
"KeyError" when running mapit_UK_import_nspd_ni

### ISSUE THREAD

**Issue by symroe** [mysociety/mapit#222]
On a new database, and revision bb2bc4adee5d5c8d496eec027aabb98ed63d4c75, after downloading the latent data for the UK from the `parlvid` cache and running the commands [on this page](http://mapit.poplus.org/docs/self-hosted/import/uk/) I get a `KeyError` raised when running 

`./manage.py mapit_UK_import_nspd_ni [path]`

The file name I'm importing is `ONSPD_NOV_2015_UK.csv`.

The exception is on line 83 of `mapit_UK_import_nspd_ni.py`: 

`ward = self.code_to_area[ons_code]`

The value of `ons_code` is `'N99999999N09000003N08000322'` (`gss` in the lines above 83 is False, meaning it's assigned on line 78 with `ons_code = ''.join(row[5:8])`).  `parl_code` is `706000002`.

This is the full row:

`['BT1 1AA', 'BT1  1AA', 'BT1 1AA', '199002', '', 'N99999999', 'N09000003', 'N08000322', '1', '334316', '0374675', '1', 'ZB001', 'N99999999', 'N92000002', 'N99999999', '0', 'N06000002', 'N07000001', 'N99999999', 'N12000002', 'ZC010', 'UKN0100020', '95Z 4001', 'Z 4001', '6', 'ZE0', '951', 'ZE0', '95Z 40', '95Z 40', '95Z 41', '99ZZ00', '95GG200003', '95GG20', 'N99999999', '95GG20S1', 'N99999999', 'A', '5B3', 'X98', 'N00001131', '95GG20S1', 'N99999999', 'N99999999', 'N99999999', 'ZC010', 'N99999999', 'N99999999', '', '2C1', '54.602444', '-5.922291', 'N99999999', 'N99999999']`

And this is the traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/symroe/.envs/mapit/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/symroe/.envs/mapit/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/symroe/.envs/mapit/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/symroe/.envs/mapit/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/symroe/.envs/mapit/lib/python3.4/site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "/Users/symroe/Projects/democracyclub/mapit/mapit_gb/management/commands/mapit_UK_import_nspd_ni.py", line 59, in handle_label
    self.process(file, options)
  File "/Users/symroe/Projects/democracyclub/mapit/mapit/management/commands/mapit_import_postal_codes.py", line 94, in process
    self._process_row(row, options)
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/symroe/Projects/democracyclub/mapit/mapit/management/commands/mapit_import_postal_codes.py", line 102, in _process_row
    if self.pre_row(row, options):
  File "/Users/symroe/Projects/democracyclub/mapit/mapit_gb/management/commands/mapit_UK_import_nspd_ni.py", line 83, in pre_row
    ward = self.code_to_area[ons_code]
KeyError: 'N99999999N09000003N08000322'
```

I'm on Python 3.4.3, OS X 10.11.2.

**Comment by dracos** [comment]
The script will not work with the latest ONSPD which uses new GSS codes for council/wards (as the comment on line 70 of the script says, it is assuming council/wards are still old codes). This should be fixed as part of #216, as we now have open boundary data for Northern Ireland.

**Comment by symroe** [comment]
Thanks – I didn't understand that the comment on line 70 related to this.  I'll keep an eye on #216

**Comment by dracos** [comment]
#216 is now merged, and the new import_onspd script should work okay, feel free to reopen if there's a bug (I've run the area commands on our MapIt, but not any ONSPD import as yet, I'll wait for the FEB 2016 release). You can also get boundaries for NI areas using the import_osni script.

**Comment by symroe** [comment]
Excellent, thanks all for the work.  I've managed to import the data from scratch using only the new commands.
