### ISSUE TITLE
Can't run manage.py mapit_UK_import_osni - files are missing from the installed package

### ISSUE THREAD

**Issue by tomkins** [mysociety/mapit#289]
After pip installing django-mapit and following the [UK data instructions](http://mapit.poplus.org/docs/self-hosted/import/uk/), the `mapit_UK_import_osni` management command results in this:

```pytb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/envs/greendale/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/mapit_gb/management/commands/mapit_UK_import_osni.py", line 94, in handle
    self.process_file(options['lge_file'], 'LGE', options['lge_srid'], control, options)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/mapit_gb/management/commands/mapit_UK_import_osni.py", line 113, in process_file
    area_code_info = getattr(self, area_code)(srid)
  File "/var/envs/greendale/local/lib/python2.7/site-packages/mapit_gb/management/commands/mapit_UK_import_osni.py", line 284, in __init__
    self._populate_osni_missing_ons_codes()
  File "/var/envs/greendale/local/lib/python2.7/site-packages/mapit_gb/management/commands/mapit_UK_import_osni.py", line 287, in _populate_osni_missing_ons_codes
    ni_areas = csv.reader(open(os.path.dirname(__file__) + '/../../data/ni-electoral-areas-2015.csv'))
IOError: [Errno 2] No such file or directory: '/var/envs/greendale/local/lib/python2.7/site-packages/mapit_gb/management/commands/../../data/ni-electoral-areas-2015.csv'
```

Certain files are missing from the installed package, as there's only one file in the data directory:

```console
$ find mapit_gb/data
mapit_gb/data
mapit_gb/data/initial-fix-ups.sql
```

There should be a few CSV/TSV files in the data directory: https://github.com/mysociety/mapit/tree/9f6f2ebce0e77a707df57093b6edcdd2fd7e62b1/mapit_gb/data

**Comment by dracos** [comment]
Hi, thanks for this! Yes, that file does appear to be missing and should be included, but not most of the files in that directory. Ideally, the packaged version should only include things necessary to the running of the current code within a packaged environment, using mapit within a Django project. It does not need to contain historical things/things only of interest, that you could get by checking out the repo (which does also contain a working project). 

It looks to me that the `recursive-include data *.csv *.sql` line was not updated when data was moved under `mapit_gb`, and updating that (plus including TSV I guess for the new local authority script) would cover more than what is needed.

As a separate point, it would perhaps make sense for the UK-specific scripts etc to be factored out to a separate repository that uses mapit to provide a cleaner separation, I've opened a new issue for that.

**Comment by dracos** [comment]
Fixed in master, won't be fixed in package until next release (hopefully right now but might not be).
