### ISSUE TITLE
Import crashes during OSNI import

### ISSUE THREAD

**Issue by matthias-mo** [mysociety/mapit#325]
I'm using mapit commit 4db8ad0830567b5bb0c9d2129375ae8bccfb3c31 and doing a data import according to http://mapit.poplus.org/docs/self-hosted/import/uk/

During OSNI import the progress stops with:

> ../data/OSNI/OSNI_Open_Data_Largescale_Boundaries__NI_Outline.shp
  New area: EUR N07000001 EUR-1 Northern Ireland
  Geometry of N07000001 EUR Northern Ireland not valid
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/matthias/mapit/mapit_build_script/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/matthias/mapit/mapit_build_script/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/matthias/mapit/mapit_build_script/env/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/matthias/mapit/mapit_build_script/env/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/matthias/mapit/mapit_build_script/mapit/mapit_gb/management/commands/mapit_UK_import_osni.py", line 104, in handle
    self.process_file(options['eur_file'], 'EUR', options['eur_srid'], control, options)
  File "/home/matthias/mapit/mapit_build_script/mapit/mapit_gb/management/commands/mapit_UK_import_osni.py", line 212, in process_file
    geos_g = fix_invalid_geos_geometry(geos_g)
  File "/home/matthias/mapit/mapit_build_script/mapit/mapit/management/command_utils.py", line 352, in fix_invalid_geos_geometry
    return fix_invalid_geos_multipolygon(geos_geometry)
  File "/home/matthias/mapit/mapit_build_script/mapit/mapit/management/command_utils.py", line 335, in fix_invalid_geos_multipolygon
    result = for_union.cascaded_union
AttributeError: 'MultiPolygon' object has no attribute 'cascaded_union'

Can you help with this?

**Comment by dracos** [comment]
That command was dropped in Django 2.0, which we say we support, so sorry about that. You should be able to run it with Django 1.11 fine in the meantime.

**Comment by matthias-mo** [comment]
Thanx, that was it!

**Comment by dracos** [comment]
I'll leave this open until it's fixed!

**Comment by torotil** [comment]
#340 would fix this.

**Comment by dracos** [comment]
Yep, now merged, thanks!
